# Generated by Django 4.2.5 on 2023-11-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Clase',
        ),
        migrations.RenameIndex(
            model_name='clase',
            new_name='tienda_clas_nombre_497c68_idx',
            old_name='tienda_prod_nombre_d4fd12_idx',
        ),
    ]
