# Generated by Django 4.2.5 on 2023-11-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_rename_producto_clase_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductoPedido',
            new_name='ClaseEnPedido',
        ),
    ]
