# Generated by Django 4.2.7 on 2023-11-20 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tienda", "0003_rename_productopedido_claseenpedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="clase",
            name="cuposActual",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="clase",
            name="cuposMaximo",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="clase",
            name="duracion",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="clase",
            name="horario",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="clase",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="clase",
            name="instructor",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="clase",
            name="nivel",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="clase",
            name="requisitos",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="clase",
            name="ubicacion",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="apellidos",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="cuentaRedSocial",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="direccion",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="numero_telefono",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="clase",
            name="nombre",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="correo",
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nombre",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="usuario",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
