# Generated by Django 4.2.7 on 2023-12-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_category_slug_alter_product_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="Stripe", max_length=200),
        ),
        migrations.AddField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[
                    ("En Espera", "En Espera"),
                    ("Pendiente de pago", "Pendiente de pago"),
                    ("Pagado", "Pagado"),
                    ("Cancelado", "Cancelado"),
                ],
                default="En Espera",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="noimage.jpg", upload_to="products/%Y/%m/%d"
            ),
        ),
    ]
