# Generated by Django 4.2.7 on 2023-12-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_image'),
        ('shop', '0003_order_state_alter_product_image'),
    ]

    operations = [
    ]
