# Generated by Django 4.2.7 on 2023-12-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_order_payment_method_order_state_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(default="No pagado", max_length=200),
        ),
    ]
