# Generated by Django 4.2.7 on 2023-12-11 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_order_payment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
    ]
