# Generated by Django 4.2.7 on 2023-12-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_remove_order_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(default="No pagado", max_length=200),
        ),
    ]
