# Generated by Django 4.2.7 on 2023-12-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quota',
            field=models.IntegerField(default=20),
        ),
    ]
