# Generated by Django 4.2.7 on 2023-12-11 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_merge_20231208_1734"),
        ("shop", "0006_order_payment_status"),
    ]

    operations = []
