# Generated by Django 4.2.7 on 2023-12-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_code'),
        ('shop', '0006_product_quota'),
    ]

    operations = [
    ]
