# Generated by Django 4.2.7 on 2023-12-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_merge_20231211_1437'),
        ('shop', '0006_order_payment_status'),
    ]

    operations = [
    ]
