# Generated by Django 4.2.7 on 2023-12-03 14:57

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_merge_0005_order_code_0006_product_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking',
            field=models.CharField(blank=True, default=shop.models.get_tracking_id, editable=False, max_length=10, unique=True),
        ),
    ]
