# Generated by Django 4.2.7 on 2023-12-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_merge_20231211_1500"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[
                    ("En Espera", "En Espera"),
                    ("Pendiente de pago", "Pendiente de pago"),
                    ("Pagado", "Pagado"),
                    ("Cancelado", "Cancelado"),
                ],
                default="En Espera",
                max_length=20,
            ),
        ),
    ]
