# Generated by Django 4.2.7 on 2023-12-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_merge_20231211_1438'),
        ('shop', '0008_alter_order_state'),
    ]

    operations = [
    ]
